### ISSUE TITLE
Implement Macro Detection Client Interface + Add support for loading captcha images

### ISSUE THREAD

**Issue by Pokye** [PandasWS/Pandas#550]
### 功能建议或构想

如果您也将这个已经在 kRO 中使用的 Anti-Bot 安全系统添加到 PandasWS，那就太好了。

### 想实现它的原因

这是一个官方的 kRO 系统，Herc 已经在他们的模拟器中实现了它。

### 参考信息

Herc Commits: https://github.com/HerculesWS/Hercules/pull/3051 / https://github.com/HerculesWS/Hercules/pull/3064

**Comment by CairoLee** [comment]
Welcome, Pokye

I believe it may be more helpful to use English to communicate with you that we have noticed this system in Hercules.

We have it lined up in the backlog, but it should take some time before we can actually get our hands on it (there are some other high priority tasks going on these days).

I can't give a specific time because the maintainers involved are putting in their own spare time. But we will as soon as possible. XD

**Comment by ssboyz** [comment]
協助備註：
[Shakto](https://rathena.org/board/profile/14926-shakto/) 已於 rAthena 發布 Anti-bot 功能編碼

資訊連結：
https://rathena.org/board/files/file/4342-anti-bot-captcha-images-from-server/
